package mapfre.automationTestsMcc.utils.enums;

public enum PerguntaPerfilEnum {

	COM_PERFIL("1"),
	SEGURADO_PRINCIPAL_CONDUTOR("2936"),
	CPF("2935"),
	CNH("9999"),
	NOME("392"),
	DATA_NASCIMENTO("393"),
	SEXO("98"),
	ESTADO_CIVIL("100"),
	PROFISSAO("240"),
	TEMPO_HABILITACAO("395"),
	TIPO_RESIDENCIA("285"),
	POSSUI_CONDUTORES_MENORES_26_ANOS("1313"),
	RESIDENTE_MENOR_26_ANOS("396"),
	FILHO_FUNCIONARIO_MENOR_26_ANOS("397"),
	QTDE_VEICULOS_RESIDENCIA("105"),
	CEP_PERNOITE("405"),
	RELACAO_COM_SEGURADO("1328"),
	VEICULO_UTILIZADO_MAIS_DOIS_DIAS("398"),
	VEICULO_ALIENADO_LEASING("106"),
	EXISTE_GARAGEM("1327"),
	EXISTE_GARAGEM_RESIDENCIA("295"),
	EXISTE_GARAGEM_TRABALHO("294"),
	EXISTE_GARAGEM_FACULDADE("296"),
	EXISTE_DISPOSITIVO_ANTIFURTO("117"),
	RASTREADORES_LOCALIZADORES("127"),
	PROPRIEDADE_RASTREADOR("407"),
	BLOQUEADORES("141"),
	DISPOSITIVO_ANTIFURTO_COMUM("140"),
	TIPO_CARROCERIA("72"),
	CARGA_TRANSPORTADA("70"),
	EQUIPAMENTO("97"),
	CABINE_SUPLEMENTAR("414"),
	VEICULO_QUANTOS_CONDUTORES("1312"),	
	AUTO_EXISTE_DISPOSITIVO_ANTIFURTO("400"),	
	CEP_RISCO_CAMINHAO("1329");
	
	private String codigo;
	
	PerguntaPerfilEnum(String codigo) {
		this.codigo = codigo;
	}

	public String getCodigo() {
		return "id_" + codigo;
	}
	
}
